version: "3"

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./db:/app/db
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - pg

  pg:
    image: postgres:12.3
    ports:
      - 5432:5432
    volumes:
      - ./db/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:6.0.6-alpine
    ports:
      - "6379:6379"

  celery:
    image: school_app
    command: celery -A School worker
