version: "3"

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./db:/app/db
    env_file:
      - .env
    environment:
      WAIT_HOSTS: pg:5432
    depends_on:
      - pg

  pg:
    image: postgres:12.3-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}

  redis:
    image: redis:6.0.6-alpine
    ports:
      - 6379:6379

  celery:
    image: otus_school_app
    command: celery -A School worker -l info
    environment:
      WAIT_HOSTS: redis:6379
    depends_on:
      - redis
